generic_worker:
  version: "v0.1"
  file_path: "py/worker/worker_configs/generic_worker.yaml"

fvs_worker:
  version: "v0.1"
  file_path: "py/worker/worker_configs/fvs_worker.yaml"

calculator_worker:
  version: "v0.1"
  file_path: "py/worker/worker_configs/calculator_worker.yaml"

addition_worker:
  version: "v0.1"
  file_path: "py/worker/worker_configs/addition_worker.yaml"

subtraction_worker:
  version: "v0.1"
  file_path: "py/worker/worker_configs/subtraction_worker.yaml"

multiplication_worker:
  version: "v0.1"
  file_path: "py/worker/worker_configs/multiplication_worker.yaml"

division_worker:
  version: "v0.1"
  file_path: "py/worker/worker_configs/division_worker.yaml"

pyrolyzer_worker:
  version: "v0.1"
  file_path: "py/worker/worker_configs/pyrolyzer_worker.yaml"
