Q_label1:
  optimizer: "bayesian_opt"
  num_questions: 1
  mode: "dsub_local_worker" #"dsub_cloud_worker" #(dsub_local, )
  workers:
    # fvs_worker : 1
    generic_worker1: 1
# Q_label2 :
#   optimizer: 'ng_bo'
#   num_questions: 7
#   mode : 'dsub_local_worker' #"dsub_cloud_worker" #(dsub_local, )
#   workers:
#     # fvs_worker : 1
#     generic_worker2 : 1

Q_label3:
  optimizer: "worklist_scheduler"
  num_questions: 2
  mode: "dsub_local_worker" #"dsub_cloud_worker" #(dsub_local, )
  workers:
    fvs_worker: 1
    # generic_worker1: 1
# Q_label3 :
#   optimizer: 'worklist_scheduler'
#   num_questions: 2
#   mode : 'dsub_local_worker' #"dsub_cloud_worker" #(dsub_local, )
#   workers:
#     # fvs_worker : 1
#     fvs_worker : 1
